import { useState } from "react";

export default function CreditDecision(){
    const decision="APPROVED";
    const score=73;
    return(
        <div className="min min-h-screen
            flex items-start justify-center
            px-4 pt-20 pb-12
            bg-gradient-to-br from-slate-900 via-primary/30 to-slate-900">
            <div className="
                w-full max-w-3xl
                bg-white
                rounded-2xl shadow-xl
                px-6 sm:px-8 lg:px-10 py-10">
                    <div className="text-center mb-8">
                        <h1 className="text-3xl font-semibold text-primary tracking-tight">Credit Decision</h1>
                        <p className="text-sm text-text/70 mt-2">
                            Based on Verified income,behaviour, and stability signals
                        </p>
                    </div>

                    <div className="flex justify-center mb-6">
                    <span className={`
                        px-4 py-2 rounded-full text-sm font-semibold tracking-wide
                        ${decision === "APPROVED" && "bg-green-500/15 text-green-600"}
                        ${decision === "REVIEW" && "bg-yellow-500/15 text-yellow-600"}
                        ${decision === "DECLINED" && "bg-red-500/15 text-red-600"}
                    `}>
                        {decision === "APPROVED" && "Approved"}
                        {decision === "REVIEW" && "Needs Manual Review"}
                        {decision === "DECLINED" && "Declined"}
                    </span>
                    </div>

                    <div className="text-center mb-10">
                        <p className="text-sm text-slate-400 mb-2">
                            Stability Index
                        </p>
                        <div className="text-5xl font-bold text-primary">
                            {score}
                            <span className="text-xl text-text/60"> / 100</span>
                        </div>
                    </div>

                    <div className="mb-10">
                        <h3 className="text-lg font-semibold mb-4">
                            Why this decision was made
                        </h3>

                        <ul className="space-y-3 text-text/80 text-sm">
                            <li>✔ Consistent income for the last 9 months</li>
                            <li>✔ Regular gig activity with predictable earnings</li>
                            <li>✔ No missed utility or rent payments in last 6 months</li>
                            <li>⚠ Moderate income variability detected</li>
                        </ul>
                    </div>

                    <div className="bg-background rounded-xl p-6 mb-8">
                    <h4 className="text-sm font-semibold mb-2">
                        What happens next
                    </h4>
                    <p className="text-sm text-text/70">
                        This decision has been cryptographically recorded.
                        Lenders can verify the outcome without accessing your private data.
                    </p>
                    </div>

                    <div className="flex flex-col sm:flex-row gap-4">
                    <button className="
                        w-full bg-primary hover:bg-secondary
                        text-white py-3 rounded-lg
                        font-semibold transition
                    ">
                        View On-Chain Audit
                    </button>

                    <button className="
                        w-full border border-white/20
                        text-white py-3 rounded-lg
                        font-semibold hover:bg-white/10 transition
                    ">
                        Improve My Score
                    </button>
                    </div>

                    <p className="text-xs text-slate-500 text-center mt-6">
                    Decision generated by Agentic AI • Hash-only audit • DPDP-aligned
                    </p>

            </div>
        </div>
    )
}